#!/bin/sh

# Package
PACKAGE="gogs"
DNAME="Gogs"

PKG_DIR="/var/packages/${DNAME}"
PERMANENT_DIR="${PKG_DIR}/etc"

SSS="/var/packages/${DNAME}/scripts/start-stop-status"
#PATH="${INSTALL_DIR}:${PATH}"

SERVICETOOL="/usr/syno/bin/servicetool"
FWPORTS="/var/packages/${DNAME}/scripts/${PACKAGE}.sc"


CUSTOM_DIR="${PERMANENT_DIR}/custom"
DATA_DIR="${PERMANENT_DIR}/data"
SETTING_FILE="${CUSTOM_DIR}/conf/app.ini"
SQLLITE_FILE="${DATA_DIR}/gogs.db"


preinst ()
{
    
    exit 0
}

postinst ()
{
    
    # Add firewall config
    #${SERVICETOOL} --install-configure-file --package ${FWPORTS} >> /dev/null

    if [[ ! -d "${CUSTOM_DIR}" ]]; then
        mkdir -p "${CUSTOM_DIR}"
    fi
    ln -s ${CUSTOM_DIR} ${SYNOPKG_PKGDEST}/gogs/
    
    if [[ ! -d "${DATA_DIR}" ]]; then
        mkdir -p "${DATA_DIR}"
    fi
    ln -s ${DATA_DIR} ${SYNOPKG_PKGDEST}/gogs/
    
    exit 0
}

preuninst ()
{
    # Stop the package
    ${SSS} stop > /dev/null
    # Remove firewall config
    #if [ "${SYNOPKG_PKG_STATUS}" == "UNINSTALL" ]; then
    #    ${SERVICETOOL} --remove-configure-file --package ${PACKAGE}.sc >> /dev/null
    #fi

    exit 0
}

postuninst ()
{
    
    exit 0
}

preupgrade ()
{
    # Stop the package
    ${SSS} stop > /dev/null
    
    exit 0
}

postupgrade ()
{
    #echo $(date)  "postupgrade" >> "${LOG_FILE}"
    
    exit 0
}
